name: CI/CD Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s app/tests

    - name: Log in to Docker Hub
      if: success()
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build Docker Image
      if: success()
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/multiply-app:v1.1 .
    - name: Push Docker Image to Docker Hub
      if: success()
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/multiply-app:v1.1